import React from "react";
import Text from "@/components/ui/Text";

const Policies = () => {
  return (
    <div className="overflow-hidden font-normal">
      <div className=" mx-auto w-full max-w-[1230px] pt-[50px] pb-[100px] px-4 text-[#ececec]">
        <Text className="text-center text-[#e3c565]">
          <strong>Last Updated: February 17, 2024</strong>
        </Text>

        <Text className="mt-4">
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use the
          Service and tells you about your privacy rights and how the law
          protects you. We use your personal data to provide and improve the
          Service. By using the Service, you agree to the collection and use of
          information in accordance with this Privacy Policy. This Privacy
          Policy has been created with the help of the Privacy Policy Generator.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Interpretation and Definitions
        </Text>
        <Text className="mt-2">
          Interpretation: The words of which the initial letter is capitalized
          have meanings defined under the following conditions. The following
          definitions shall have the same meaning regardless of whether they
          appear in singular or in plural.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Definitions
        </Text>
        <Text as="h3" className="mt-2">
          For the purposes of this Privacy Policy:
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Account
        </Text>
        <Text className="mt-2">
          Means a unique account created for you to access our Service or parts
          of our Service. Company (referred to as either the Company, We, Us or
          Our in this Agreement) refers to, 6262 Glade Avenue.
        </Text>

        {/* Duplicate Account block if needed */}
        <Text as="h3" className="mt-6 text-[22px]">
          Account
        </Text>
        <Text className="mt-2">
          Means a unique account created for you to access our Service or parts
          of our Service. Company (referred to as either the Company, We, Us or
          Our in this Agreement) refers to, 6262 Glade Avenue.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Cookies
        </Text>
        <Text className="mt-2">
          Are small files that are placed on your computer, mobile device or any
          other device by a website, containing the details of your browsing
          history on that website among its many uses. Country refers to:
          Florida, United States.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Device
        </Text>
        <Text className="mt-2">
          Means any device that can access the Service such as a computer, a
          cellphone or a digital tablet. Personal Data is any information that
          relates to an identified or identifiable individual.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Service
        </Text>
        <Text className="mt-2">
          Refers to the Website, Innovative MOJO, accessible from
          innovativemojo.com.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Service Provider
        </Text>
        <Text className="mt-2">
          Means any natural or legal person who processes the data on behalf of
          the Company. It refers to third-party companies or individuals
          employed by the Company to facilitate the Service, to provide the
          Service on behalf of the Company, to perform services related to the
          Service, or to assist the Company in analyzing how the Service is
          used.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Usage Data
        </Text>
        <Text className="mt-2">
          Refers to data collected automatically, either generated by the use of
          the Service or from the Service infrastructure itself (for example,
          the duration of a page visit). When you access the Service by or
          through a mobile device, we may collect certain information
          automatically, including but not limited to, the type of mobile device
          you use, your mobile device unique ID, the IP address of your mobile
          device, your mobile operating system, the type of mobile Internet
          browser you use, unique device identifiers, and other diagnostic data.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Tracking Technologies and Cookies
        </Text>
        <Text className="mt-2">
          We use Cookies and similar tracking technologies to track the activity
          on our Service and store certain information. The technologies we use
          may include: Cookies or Browser Cookies, Flash Cookies, and Web
          Beacons. Cookies can be Persistent or Session Cookies.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Use of Your Personal Data
        </Text>
        <Text className="mt-2">
          The Company may use Personal Data for the following purposes: to
          provide and maintain our Service (including monitoring its usage); to
          manage your account; for the performance of a contract; to contact
          you; to provide you with news, special offers and general information
          about other goods, services, and events; to manage your requests; for
          business transfers; and for other purposes such as data analysis,
          identifying usage trends, determining the effectiveness of our
          promotional campaigns, and to evaluate and improve our Service,
          products, services, marketing, and your experience.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Sharing Your Personal Data
        </Text>
        <Text className="mt-2">
          We may share your personal information in the following situations:
          with Service Providers; for business transfers; with Affiliates; with
          business partners; with other users when you share personal
          information in public areas; and with your consent for any other
          purpose.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Retention of Your Personal Data
        </Text>
        <Text className="mt-2">
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations, resolve disputes, and enforce our legal
          agreements and policies. The Company will also retain Usage Data for
          internal analysis purposes.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Transfer of Your Personal Data
        </Text>
        <Text className="mt-2">
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located. This means that your
          information may be transferred to—and maintained on—computers located
          outside of your jurisdiction. Your consent to this Privacy Policy
          followed by your submission of such information represents your
          agreement to that transfer.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Disclosure of Your Personal Data
        </Text>
        <Text className="mt-2">
          Business Transactions: If the Company is involved in a merger,
          acquisition, or asset sale, your Personal Data may be transferred. We
          will provide notice before your Personal Data is transferred and
          becomes subject to a different Privacy Policy.
        </Text>
        <Text className="mt-2">
          Law Enforcement: Under certain circumstances, the Company may be
          required to disclose your Personal Data if required to do so by law or
          in response to valid requests by public authorities.
        </Text>
        <Text className="mt-2">
          Other Legal Requirements: The Company may disclose your Personal Data
          in the good faith belief that such action is necessary to comply with
          a legal obligation, protect and defend the rights or property of the
          Company, prevent or investigate possible wrongdoing in connection with
          the Service, protect the personal safety of users of the Service or
          the public, or protect against legal liability.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Security of Your Personal Data
        </Text>
        <Text className="mt-2">
          The security of your Personal Data is important to us, but no method
          of transmission over the Internet or method of electronic storage is
          100% secure. While we strive to use commercially acceptable means to
          protect your Personal Data, we cannot guarantee its absolute security.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Children&apos;s Privacy
        </Text>
        <Text className="mt-2">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If you are a parent or guardian and you are aware
          that your child has provided us with Personal Data, please contact us.
          If we become aware that we have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, we take
          steps to remove that information from our servers.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Links to Other Websites
        </Text>
        <Text className="mt-2">
          Our Service may contain links to other websites that are not operated
          by us. If you click on a third-party link, you will be directed to
          that third party’s site. We strongly advise you to review the Privacy
          Policy of every site you visit. We have no control over and assume no
          responsibility for the content, privacy policies, or practices of any
          third-party sites or services.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Changes to this Privacy Policy
        </Text>
        <Text className="mt-2">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page. We will
          also notify you via email and/or a prominent notice on our Service
          before the change becomes effective and update the Last Updated date
          at the top of this Privacy Policy. You are advised to review this
          Privacy Policy periodically for any changes. Changes to this Privacy
          Policy are effective when they are posted on this page.
        </Text>

        <Text as="h3" className="mt-6 text-[22px]">
          Contact Us
        </Text>
        <Text className="mt-2">
          If you have any questions about this Privacy Policy, you can contact
          us by email:{" "}
          <a
            href="mailto:eric@innovativemojo.com"
            className="underline text-[#f1f4fa]"
          >
            eric@innovativemojo.com
          </a>
        </Text>
      </div>
    </div>
  );
};

export default Policies;
